### ISSUE TITLE
security bug in pip version?

### ISSUE THREAD

**Issue by dave31415** [HDFGroup/hdf5-json#61]
I installed from pip
Typing the command
h5tojson.py outputs/autoencoder_model.h5

gives me a bunch of error messages including

from: can't read /var/mail/h5json

Why is it trying to read from my mail folder?

The package build from scratch doesn't have this problem. Please update pip.

**Comment by jreadey** [comment]
I suspect that the command was being interpreted as a bash script rather than python.

What happens if you run: ``python /usr/local/bin/h5tojson.py output/autoenconder_model.h5``  ?

The setup script needs some improvement - it should be "h5tojson" that is put into the path as an app by the installer.

**Comment by dave31415** [comment]
Yeah. The file is indeed a long python script but with no #!/bin/python on top. 
Calling this, as you suggest, works fine.
python /usr/local/bin/h5tojson.py output/autoenconder_model.h5

The one I build from git is a short python script and it works

#!/usr/local/bin/python
# EASY-INSTALL-SCRIPT: 'h5json==1.1.1','h5tojson.py'
__requires__ = 'h5json==1.1.1'
__import__('pkg_resources').run_script('h5json==1.1.1', 'h5tojson.py')

**Comment by jreadey** [comment]
I've updated setup so that install puts "h5tojson" and "jsontoh5" in the path.
